### ISSUE TITLE
[BUG] Find function does not work

### ISSUE THREAD

**Issue by matemargit** [webmaster442/Money#7]
**Reproduction steps:**
1. Insert new data, e.g: `money add 2000 -t "Frei kávézó, Kati", -c "extra" -d "2023.02.08"`
2. Search for the newly added data's description, e.g: `money find "Frei"`

**Result:**
* Search does not find anything for the given text
![image](https://user-images.githubusercontent.com/18399908/217652609-b009bd2a-2c1e-4625-8d95-b6cb9cbf18ec.png)

**Expected:**
* Search should find the newly inserted spending (and all which has contains the given keyword)

**Comment by webmaster442** [comment]
Fixed
